# Generated by Django 5.1.6 on 2025-03-05 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invista-me', '0002_investimento_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investimento',
            name='nivel',
        ),
    ]
